.SUFFIXES: .erl .beam .yrl

.erl.beam:
	erlc -W $<

.yrl.erl:
	erlc -W $<

ERL = erl -boot start_clean

# コンパイルしたいErlangモジュールのリストをここに記述
MODS = module1 moduld2 \
	   module3 module4

all: compile

compile: ${MODS:%=%.beam} subdirs

# 特別なコンパイル
speciall.beam: speciall erl ${ERL} -pa Dir1 -s application1 start Arg1 Arg2

subdirs:
	cd dir1; make
	cd dir2; make

clean:
	rm -rf *.beam erl_crash.dump
	cd dir1; make clean
	cd dir2; make clean
